nginx:
    image: nginx:latest
    ports:
        - "8000:80"
    volumes:
        - ./:/data-driven-test-development-demo
        - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    links:
        - fpm

fpm:
    build: .
    links:
        - mysql
    volumes:
        - ./:/data-driven-test-development-demo

mysql:
    image: mysql:5.7
    environment:
        - DB_HOST=mysql
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=ddtd_demo
