version: "3.5"

services:
  php_fpm:
      build: .
      container_name: ddtd_demo_php_fpm
      working_dir: /usr/share/nginx/ddtd-demo
      networks:
        - ddtd_demo
      volumes:
          - ./:/usr/share/nginx/ddtd-demo

  nginx:
      image: nginx:1.15
      container_name: ddtd_demo_nginx
      working_dir: /usr/share/nginx/ddtd-demo
      networks:
        - ddtd_demo
      ports:
          - "8080:80"
      volumes:
          - ./:/usr/share/nginx/ddtd-demo
          - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
      image: mysql:5.7
      container_name: ddtd_demo_mysql
      networks:
        - ddtd_demo
      environment:
          - MYSQL_ROOT_PASSWORD=password
          - MYSQL_DATABASE=ddtd_demo

networks:
  ddtd_demo:
    driver: bridge
